apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "25.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    server:
      persistentVolume:
        enabled: true
        size: 8Gi
    alertmanager:
      persistentVolume:
        enabled: true
        size: 2Gi
    ingress:
      enabled: true
      ingressClassName: nginx 